# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j2"
ACCEPT_LICENSE="*"
FEATURES="getbinpkg binpkg-request-signature"

# NOTE: This stage was built with the bindist USE flag enabled
USE="
	wayland gtk qt flatpak xdg gui
	networkmanager modemmanager wifi bluetooth libnotify
	policykit udev dbus systemd verify-sig
	btrfs lz4 udisks archive 
	vaapi opengl 
	zsh-completion
	-openrc -elogind
"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
